### ISSUE TITLE
[Bug] Doesn't work with Sodium 0.5.x

### ISSUE THREAD

**Issue by vukkax** [DM-Earth/flywheel-fabric-dme-edition#1]
### Describe the Bug

**EDIT: It seems the issue only happens when using _Sodium 0.5.x_ alongisde those two, _Hephaestus and Create DM-Earth work fine_**

As the title says, when using latest Fabric Version, Fabric API, Create DM-Earth Fix and Hephaestus the game crashes, which it shouldn't happen since the purpose of this fix is compatibility for those two mods.

**CRASH REPORT:**
[crash-2023-10-07_17.33.10-client.txt](https://github.com/DM-Earth/create-fabric-dme-edition/files/12838145/crash-2023-10-07_17.33.10-client.txt)

### Reproduction Steps

1. Install Fabric API
2. Install Create DM-Fix
3. Install Sodium 0.5.3
4. Install Hephaestus 3.6.3.232
5. Open Game
6. Crash
7. Sadge :(
...

### Expected Result

Not crash :)

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

![image](https://github.com/DM-Earth/create-fabric-dme-edition/assets/108903683/5d52018d-7ecf-45bb-9840-9cd030ca30c3)

**Comment by TexBlock** [comment]
Flywheel Fabric DM-Earth Edition issue, i will move to there repo

**Comment by TexBlock** [comment]
fixed in flywheel `0.6.10`
